COLLECTION_UNKNOWN = "unknown"
COLLECTION_PLACES = "places"
COLLECTION_FAMILY_NAMES = "familyNames"
COLLECTION_MOVIES = "movies"
COLLECTION_PERSONALITIES = "personalities"
COLLECTION_PHOTOUNITS = "photoUnits"
ALL_KNOWN_COLLECTIONS = [COLLECTION_PLACES, COLLECTION_FAMILY_NAMES, COLLECTION_MOVIES,
                         COLLECTION_PERSONALITIES, COLLECTION_PHOTOUNITS]
